from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Iterable


POLICY_AI_PROHIBITED = "AI_GENERATED_PROHIBITED"
POLICY_REPO_RULES = "REPOSITORY_RULES_REQUIRED"
INGEST_MANUAL_ONLY = "MANUAL_PROBLEM_TEXT_ONLY"
INGEST_CONNECTOR = "AUTHORIZED_CONNECTOR_ONLY"


@dataclass(frozen=True)
class SourcePolicy:
    source: str
    publication_mode: str
    ingestion_mode: str
    automated_publication: bool
    policy_url: str
    checked_on: str
    note: str

    def to_dict(self) -> dict:
        return asdict(self)


SOURCE_POLICIES: dict[str, SourcePolicy] = {
    "stackoverflow": SourcePolicy(
        source="stackoverflow",
        publication_mode=POLICY_AI_PROHIBITED,
        ingestion_mode=INGEST_MANUAL_ONLY,
        automated_publication=False,
        policy_url="https://stackoverflow.com/help/gen-ai-policy",
        checked_on="2026-09-18",
        note="Use only user-supplied problem text for this workflow; do not scrape or auto-post.",
    ),
    "mathoverflow": SourcePolicy(
        source="mathoverflow",
        publication_mode=POLICY_AI_PROHIBITED,
        ingestion_mode=INGEST_MANUAL_ONLY,
        automated_publication=False,
        policy_url="https://mathoverflow.net/help/gen-ai-policy",
        checked_on="2026-09-18",
        note="Core mathematical content must not be generated by AI for publication.",
    ),
    "physics-stackexchange": SourcePolicy(
        source="physics-stackexchange",
        publication_mode=POLICY_AI_PROHIBITED,
        ingestion_mode=INGEST_MANUAL_ONLY,
        automated_publication=False,
        policy_url="https://physics.meta.stackexchange.com/questions/15065/the-rise-of-llm-powered-users",
        checked_on="2026-09-18",
        note="Current local policy prohibits generated content; keep the foundry as an internal verifier only.",
    ),
    "github": SourcePolicy(
        source="github",
        publication_mode=POLICY_REPO_RULES,
        ingestion_mode=INGEST_CONNECTOR,
        automated_publication=False,
        policy_url="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
        checked_on="2026-09-18",
        note="Repository contribution rules and maintainer expectations must be checked before any public action.",
    ),
}


DOMAIN_CONTRACTS: dict[str, tuple[str, ...]] = {
    "code": (
        "minimal_reproducer",
        "unit_tests",
        "regression_tests",
        "static_or_type_checks_when_applicable",
        "benchmark_when_performance_is_claimed",
    ),
    "math": (
        "explicit_assumptions",
        "counterexample_search",
        "symbolic_or_exact_cross_check",
        "numerical_sanity_check_when_applicable",
        "formal_proof_or_human_proof_review_for_certification",
    ),
    "physics": (
        "dimensional_analysis",
        "limiting_cases",
        "conservation_or_symmetry_checks",
        "numerical_cross_check",
        "literature_and_measurement_boundary",
    ),
    "engineering": (
        "requirements",
        "failure_modes",
        "simulation_or_model_check",
        "test_plan",
        "safety_and_operating_limits",
    ),
    "data": (
        "dataset_provenance",
        "schema_validation",
        "statistical_sanity_checks",
        "leakage_and_bias_checks",
        "reproducible_analysis",
    ),
}


DOMAIN_COMPONENTS: dict[str, tuple[str, ...]] = {
    "code": ("HGFM_ROUTER", "AI7_SOLVER", "DCT_OMEGA", "OAK_SOFTWARE"),
    "math": ("HGFM_ROUTER", "TFACC", "AI7_FALSIFIER", "OAK_MATH"),
    "physics": ("HGFM_ROUTER", "OMEGA_PHYSICS_DEFECT_FOUNDRY", "AI7_FALSIFIER", "OAK_PHYSICS"),
    "engineering": ("HGFM_ROUTER", "AI7_SOLVER", "FAILURESYNTH", "OAK_ENGINEERING"),
    "data": ("HGFM_ROUTER", "AI7_ANALYST", "DCT_OMEGA", "OAK_DATA"),
}


@dataclass(frozen=True)
class ProblemGenome:
    problem_id: str
    source: str
    title: str
    domain: str
    body: str = ""
    tags: tuple[str, ...] = ()
    languages: tuple[str, ...] = ()
    utility: float = 1.0
    generalization: float = 1.0
    verifiability: float = 1.0
    diversity: float = 1.0
    unanswered_signal: float = 0.0
    reuse_potential: float = 1.0
    effort: float = 1.0
    risk: float = 0.0

    def validate(self) -> tuple[str, ...]:
        errors: list[str] = []
        if not self.problem_id.strip():
            errors.append("problem_id required")
        if not self.title.strip():
            errors.append("title required")
        if self.source not in SOURCE_POLICIES:
            errors.append(f"unknown source policy: {self.source}")
        if self.domain not in DOMAIN_CONTRACTS:
            errors.append(f"unknown domain: {self.domain}")
        for name in (
            "utility",
            "generalization",
            "verifiability",
            "diversity",
            "unanswered_signal",
            "reuse_potential",
            "effort",
            "risk",
        ):
            if getattr(self, name) < 0:
                errors.append(f"{name} must be non-negative")
        return tuple(errors)

    @property
    def verified_value(self) -> float:
        return (
            2.0 * self.utility
            + 2.0 * self.generalization
            + 2.0 * self.verifiability
            + 1.5 * self.diversity
            + 1.0 * self.unanswered_signal
            + 1.5 * self.reuse_potential
        )

    @property
    def burden(self) -> float:
        return max(self.effort + self.risk, 1e-9)

    @property
    def base_score(self) -> float:
        return self.verified_value / self.burden

    def to_dict(self) -> dict:
        payload = asdict(self)
        payload["base_score"] = self.base_score
        return payload


@dataclass(frozen=True)
class ProblemPlan:
    schema_version: str
    problem: dict
    policy: dict
    components: tuple[str, ...]
    verification_contract: tuple[str, ...]
    publication_allowed: bool
    publication_blockers: tuple[str, ...]
    epistemic_status: str

    def to_dict(self) -> dict:
        return asdict(self)


def compile_problem_plan(problem: ProblemGenome) -> ProblemPlan:
    errors = problem.validate()
    if errors:
        raise ValueError("; ".join(errors))

    policy = SOURCE_POLICIES[problem.source]
    blockers: list[str] = []
    if policy.publication_mode == POLICY_AI_PROHIBITED:
        blockers.append("AI_GENERATED_PUBLICATION_PROHIBITED")
    if policy.publication_mode == POLICY_REPO_RULES:
        blockers.append("REPOSITORY_RULES_NOT_YET_VERIFIED")
    if not policy.automated_publication:
        blockers.append("AUTOMATED_PUBLICATION_DISABLED")

    return ProblemPlan(
        schema_version="tristan-problem-foundry-r1",
        problem=problem.to_dict(),
        policy=policy.to_dict(),
        components=DOMAIN_COMPONENTS[problem.domain],
        verification_contract=DOMAIN_CONTRACTS[problem.domain],
        publication_allowed=not blockers,
        publication_blockers=tuple(blockers),
        epistemic_status="PROVISIONAL_ENGINEERING_PLAN",
    )


def rank_diverse_problems(problems: Iterable[ProblemGenome]) -> list[ProblemGenome]:
    remaining = list(problems)
    for problem in remaining:
        errors = problem.validate()
        if errors:
            raise ValueError(f"{problem.problem_id}: {'; '.join(errors)}")

    selected: list[ProblemGenome] = []
    domain_counts: dict[str, int] = {}
    while remaining:
        def score(problem: ProblemGenome) -> tuple[float, float, str]:
            domain_bonus = 1.0 / (1.0 + domain_counts.get(problem.domain, 0))
            diversified = problem.base_score * (1.0 + 0.35 * domain_bonus)
            return diversified, problem.generalization, problem.problem_id

        best = max(remaining, key=score)
        selected.append(best)
        domain_counts[best.domain] = domain_counts.get(best.domain, 0) + 1
        remaining.remove(best)
    return selected


def problem_family_signature(problem: ProblemGenome) -> tuple[str, tuple[str, ...], tuple[str, ...]]:
    return (
        problem.domain,
        tuple(sorted(set(problem.tags))),
        tuple(sorted(set(problem.languages))),
    )
